"""
TrialGuard seed script.

Drops and recreates the SQLite database, then populates it with the complete
synthetic dataset generated by synthetic_data.py.

Usage (from repository root):
    python -m src.backend.seed.seed

Or:
    python src/backend/seed/seed.py

The script is idempotent: running it multiple times always produces the same
database state because the data generators use a fixed random seed.

IMPORTANT: This script destroys and recreates all data on each run.
Do NOT point it at a production database.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure the repository root is on sys.path so that `src.backend` imports work
# when the script is run directly (not as a module).
_repo_root = Path(__file__).resolve().parents[4]
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from sqlalchemy import select

from src.backend.config import settings
from src.backend.db import SessionLocal, init_db
from src.backend.models import (
    AdverseEvent,
    ClinicalTrial,
    Patient,
    PatientStatus,
    Site,
    SiteStatus,
    Visit,
    VisitType,
    LabResult,
)
from src.backend.seed.synthetic_data import generate_all


def _ensure_data_dir() -> None:
    """Create the data directory if it does not exist."""
    if not settings.resolved_database_url.startswith("sqlite"):
        return
    db_path = Path(settings.database_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)


def seed(*, reset: bool = True) -> None:
    print("=" * 60)
    print("TrialGuard -- Seed Script")
    print("=" * 60)
    print(f"Database : {settings.database_path}")
    print(f"Protocol : {settings.protocol_path}")
    print()

    # 1. Ensure data directory exists
    _ensure_data_dir()

    # 2. Create schema. Reset is deliberately opt-in for production safety.
    print(f"Initialising database schema (drop_existing={reset})...")
    init_db(drop_existing=reset)
    print("  [OK] Schema created.\n")

    # 3. Generate synthetic data
    # We generate twice: once with _id stripped (for site/patient/visit/AE inserts),
    # and once raw (with _id intact) for cross-referencing lab results to visit IDs.
    print("Generating synthetic dataset...")

    # Raw generation: visits and lab_results still carry internal _id keys
    from src.backend.seed.synthetic_data import (
        generate_trial,
        generate_sites,
        generate_patients,
        generate_visits,
        generate_lab_results,
        generate_adverse_events,
    )
    import random
    random.seed(42)

    raw_trial = generate_trial()
    raw_sites = generate_sites(raw_trial["id"])
    raw_patients = generate_patients(raw_sites, raw_trial["id"])
    raw_visits = generate_visits(raw_patients)           # visits with _id keys
    raw_labs = generate_lab_results(raw_patients, raw_visits)   # labs with seq visit_id
    raw_aes = generate_adverse_events(raw_patients, raw_visits)

    print(f"  [OK] Generated:")
    print(f"      1 trial")
    print(f"      {len(raw_sites)} sites")
    print(f"      {len(raw_patients)} patients")
    print(f"      {len(raw_visits)} visits")
    print(f"      {len(raw_labs)} lab results")
    print(f"      {len(raw_aes)} adverse events")
    print()

    # 4. Insert into database
    print("Inserting records...")
    db = SessionLocal()
    try:
        # -- Trial --
        t = raw_trial
        trial = ClinicalTrial(
            id=t["id"],
            name=t["name"],
            protocol_version=t["protocol_version"],
            sponsor=t["sponsor"],
            phase=t["phase"],
            indication=t["indication"],
            start_date=t["start_date"],
            end_date=t["end_date"],
            target_enrollment=t["target_enrollment"],
            primary_endpoint=t["primary_endpoint"],
        )
        db.add(trial)
        db.flush()
        print(f"  [OK] Trial: {trial.id}")

        # -- Sites --
        for s in raw_sites:
            site = Site(
                id=s["id"],
                trial_id=s["trial_id"],
                name=s["name"],
                city=s["city"],
                country=s["country"],
                principal_investigator=s["principal_investigator"],
                status=SiteStatus.ACTIVE,
                enrolled_count=s["enrolled_count"],
                target_enrollment=s["target_enrollment"],
                activation_date=s["activation_date"],
            )
            db.add(site)
        db.flush()
        print(f"  [OK] Sites: {len(raw_sites)}")

        # -- Patients --
        for p in raw_patients:
            patient = Patient(
                id=p["id"],
                site_id=p["site_id"],
                trial_id=p["trial_id"],
                age=p["age"],
                sex=p["sex"],
                ecog_score=p["ecog_score"],
                diagnosis_confirmed=p["diagnosis_confirmed"],
                prior_egfr_alk_treatment_days=p["prior_egfr_alk_treatment_days"],
                active_infection=p["active_infection"],
                pregnant_or_breastfeeding=p["pregnant_or_breastfeeding"],
                consent_signed_before_procedure=p["consent_signed_before_procedure"],
                enrollment_date=p["enrollment_date"],
                status=PatientStatus.ENROLLED,
            )
            db.add(patient)
        db.flush()
        print(f"  [OK] Patients: {len(raw_patients)}")

        # -- Visits --
        # Insert visits and build a map: (patient_id, visit_number) -> DB visit.id
        for v in raw_visits:
            visit = Visit(
                patient_id=v["patient_id"],
                site_id=v["site_id"],
                visit_number=v["visit_number"],
                visit_name=v["visit_name"],
                visit_type=VisitType.SCHEDULED,
                scheduled_date=v["scheduled_date"],
                actual_date=v["actual_date"],
                window_deviation_days=v["window_deviation_days"],
                completed_assessments=v["completed_assessments"],
                notes=v["notes"],
            )
            db.add(visit)
        db.flush()

        # Build lookup from DB-assigned IDs: (patient_id, visit_number) -> db_visit_id
        visit_id_map: dict[tuple[str, int], int] = {}
        rows = db.execute(select(Visit.id, Visit.patient_id, Visit.visit_number)).all()
        for row in rows:
            visit_id_map[(row.patient_id, row.visit_number)] = row.id

        print(f"  [OK] Visits: {len(raw_visits)}")

        # -- Lab Results --
        # raw_visits carry _id (sequential synthetic counter).
        # Build: seq_id -> (patient_id, visit_number)
        seq_to_key: dict[int, tuple[str, int]] = {}
        for rv in raw_visits:
            seq_to_key[rv["_id"]] = (rv["patient_id"], rv["visit_number"])

        for lr in raw_labs:
            p_id, v_num = seq_to_key[lr["visit_id"]]
            real_visit_id = visit_id_map[(p_id, v_num)]
            lab = LabResult(
                patient_id=lr["patient_id"],
                visit_id=real_visit_id,
                test_name=lr["test_name"],
                display_name=lr["display_name"],
                value=lr["value"],
                unit=lr["unit"],
                reference_low=lr["reference_low"],
                reference_high=lr["reference_high"],
                collection_date=lr["collection_date"],
                is_out_of_range=lr["is_out_of_range"],
            )
            db.add(lab)
        db.flush()
        print(f"  [OK] Lab results: {len(raw_labs)}")

        # -- Adverse Events --
        for ae_data in raw_aes:
            ae = AdverseEvent(
                patient_id=ae_data["patient_id"],
                site_id=ae_data["site_id"],
                description=ae_data["description"],
                onset_date=ae_data["onset_date"],
                sae_flag=ae_data["sae_flag"],
                expected_flag=ae_data["expected_flag"],
                reported_date=ae_data["reported_date"],
                reporting_delay_hours=ae_data["reporting_delay_hours"],
                severity_grade=ae_data["severity_grade"],
                outcome=ae_data["outcome"],
            )
            db.add(ae)
        db.flush()
        print(f"  [OK] Adverse events: {len(raw_aes)}")

        db.commit()
        print()
        print("  [OK] All records committed.\n")

    except Exception as exc:
        db.rollback()
        print(f"\n  [ERROR] during seeding: {exc}")
        raise
    finally:
        db.close()

    # 5. Verification summary
    print("Verification summary:")
    db2 = SessionLocal()
    try:
        from sqlalchemy import func

        counts = {
            "trials":         db2.execute(select(func.count()).select_from(ClinicalTrial)).scalar(),
            "sites":          db2.execute(select(func.count()).select_from(Site)).scalar(),
            "patients":       db2.execute(select(func.count()).select_from(Patient)).scalar(),
            "visits":         db2.execute(select(func.count()).select_from(Visit)).scalar(),
            "lab_results":    db2.execute(select(func.count()).select_from(LabResult)).scalar(),
            "adverse_events": db2.execute(select(func.count()).select_from(AdverseEvent)).scalar(),
        }
        for entity, count in counts.items():
            print(f"  {entity:<20} {count}")

        # Special verification: PT-0042
        pt42 = db2.execute(
            select(Patient).where(Patient.id == "PT-0042")
        ).scalar_one_or_none()
        if pt42:
            age_ok = pt42.age == 76
            site_ok = pt42.site_id == "SITE-003"
            print(f"\n  PT-0042:")
            print(f"    age       = {pt42.age}  {'[OK]' if age_ok else '[FAIL] EXPECTED 76'}")
            print(f"    site_id   = {pt42.site_id}  {'[OK]' if site_ok else '[FAIL] EXPECTED SITE-003'}")
        else:
            print("\n  [FAIL] PT-0042 NOT FOUND")

        # Site 003 and 005
        s3 = db2.get(Site, "SITE-003")
        s5 = db2.get(Site, "SITE-005")
        print(f"\n  SITE-003: {'[OK] found -- ' + s3.name if s3 else '[FAIL] NOT FOUND'}")
        print(f"  SITE-005: {'[OK] found -- ' + s5.name if s5 else '[FAIL] NOT FOUND'}")

    finally:
        db2.close()

    print()
    print("=" * 60)
    print("Seed complete.")
    print("=" * 60)


def seed_if_empty() -> bool:
    """Create the deterministic demo data once without deleting existing records.

    This is intended for explicit production initialization. Runtime requests must
    never call it: Vercel functions are ephemeral, while the managed database is
    persistent. Returns True only when it inserted the initial dataset.
    """
    init_db(drop_existing=False)
    db = SessionLocal()
    try:
        has_trial = db.execute(select(ClinicalTrial.id).limit(1)).scalar_one_or_none()
    finally:
        db.close()

    if has_trial:
        print("Existing TrialGuard data found; skipping seed.")
        return False

    seed(reset=False)
    return True


if __name__ == "__main__":
    seed()
