"""
Reports router — GET /api/reports/site/{id}
"""
from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import func
from sqlalchemy.orm import Session

from src.backend.db import get_db
from src.backend.models import CAPA, CAPAStatus, Deviation, DeviationStatus, Patient, Site, SiteRiskScore
from src.backend.schemas import SiteReportResponse

router = APIRouter(prefix="/api/reports", tags=["reports"])


@router.get("/site/{site_id}", response_model=SiteReportResponse)
def get_site_report(site_id: str, db: Session = Depends(get_db)):
    """
    Generate a Markdown monitoring report for a site, suitable for printing
    or pasting into a CRF audit document.
    """
    site = db.query(Site).filter(Site.id == site_id).first()
    if not site:
        raise HTTPException(status_code=404, detail=f"Site {site_id} not found")

    # Latest risk score
    risk = (
        db.query(SiteRiskScore)
        .filter(SiteRiskScore.site_id == site_id)
        .order_by(SiteRiskScore.score_date.desc())
        .first()
    )

    # Deviation counts
    dev_counts = (
        db.query(Deviation.severity, Deviation.status, func.count(Deviation.id))
        .filter(Deviation.site_id == site_id)
        .group_by(Deviation.severity, Deviation.status)
        .all()
    )

    open_devs = (
        db.query(Deviation)
        .filter(Deviation.site_id == site_id, Deviation.status == DeviationStatus.OPEN)
        .order_by(Deviation.severity, Deviation.detected_date)
        .limit(30)
        .all()
    )

    # Open CAPAs
    open_capas = (
        db.query(CAPA)
        .filter(CAPA.site_id == site_id, CAPA.status != CAPAStatus.CLOSED)
        .all()
    )

    # Patient count
    patient_count = (
        db.query(func.count(Patient.id))
        .filter(Patient.site_id == site_id)
        .scalar()
    )

    now = datetime.utcnow()

    # Build markdown
    lines = [
        f"# Site Monitoring Report — {site.name}",
        f"",
        f"**Site ID:** {site.id}  ",
        f"**Principal Investigator:** {site.principal_investigator}  ",
        f"**Location:** {site.city}, {site.country}  ",
        f"**Enrolled:** {site.enrolled_count} / {site.target_enrollment}  ",
        f"**Report Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"",
        f"---",
        f"",
        f"## Risk Score",
        f"",
    ]

    if risk:
        lines += [
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| **Total Score** | **{risk.total_score:.1f}** |",
            f"| Risk Tier | **{risk.risk_tier}** |",
            f"| Major Open Deviations | {risk.major_open_count} |",
            f"| Minor Open Deviations | {risk.minor_open_count} |",
            f"| Administrative Open Deviations | {risk.admin_open_count} |",
            f"| Avg CAPA Age (days) | {risk.avg_capa_age_days:.0f} |",
            f"| Data Query Rate | {risk.data_query_rate_pct:.1f}% |",
            f"| Enrollment Deviation | {risk.enrollment_deviation_pct:.1f}% |",
            f"",
        ]
    else:
        lines.append("_No risk score available. Run analysis first._\n")

    lines += [
        f"---",
        f"",
        f"## Open Deviations ({len(open_devs)} shown)",
        f"",
        f"| ID | Patient | Rule | Severity | Detected | Description |",
        f"|----|---------|------|----------|----------|-------------|",
    ]

    for d in open_devs:
        desc = d.description[:60] + "..." if len(d.description) > 60 else d.description
        lines.append(
            f"| {d.id} | {d.patient_id} | {d.rule_id} | {d.severity} "
            f"| {d.detected_date} | {desc} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"## Open CAPAs ({len(open_capas)})",
        f"",
    ]

    if open_capas:
        lines.append("| CAPA ID | Deviation ID | Status | Due Date |")
        lines.append("|---------|--------------|--------|----------|")
        for c in open_capas:
            lines.append(f"| {c.id} | {c.deviation_id} | {c.status} | {c.due_date or 'N/A'} |")
    else:
        lines.append("_No open CAPAs._")

    lines += [
        f"",
        f"---",
        f"",
        f"*Report generated by TrialGuard. Deviations are based on deterministic rule evaluation against protocol v{' '}.*",
    ]

    return SiteReportResponse(
        site_id=site_id,
        report_markdown="\n".join(lines),
        generated_at=now,
    )
